### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by s4ke** [olljanat/csi-plugins-for-docker-swarm#2]
Hey @olljanat ,

could you add a (hopefully) permissive license to this repo, so we can take the example code you already worked on to build out the PRs in the other repos? This will make contributing much easier :)

Thanks!

**Comment by s4ke** [comment]
Asking because I am working on a PR for Hetzner here: https://github.com/hetznercloud/csi-driver/pull/376 and would very much would draw inspiration from your work.

**Comment by olljanat** [comment]
There is MIT license already.

**Comment by s4ke** [comment]
Ah, sorry. I overlooked this one. Thanks.
